version: '3.7'
services:
  4invoices:
    build: .
    restart: ${CONTAINER_NAME_APP_RESTART}
    container_name: ${CONTAINER_NAME_APP}
    ports:
      - '${CONTAINER_NAME_APP_PORT}:${PORT}'
    depends_on:
      - database

  database:
    image: postgres:15
    restart: ${CONTAINER_NAME_DB_RESTART}
    container_name: ${CONTAINER_NAME_DB}
    ports:
     - '${CONTAINER_NAME_DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
